

# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password: root
#   socket: /var/run/mysqld/mysqld.sock

# development:
#   <<: *default
#   database: logistics_development

# test:
#   <<: *default
#   database: logistics_test

# production:
#   <<: *default
#   database: logistics_prod
#   username: log_manager
#   password: <%= ENV["LOGISTICS_APP_DATABASE_PASSWORD"] %>

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASS']%>
  host: <%=ENV['DB_HOST']%>
  port: <%=ENV['DB_PORT']%>
  ssl: REQUIRED
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: logistics_app_dev

test:
  <<: *default
  database: logistics_app_test

production:
  <<: *default
  database: logistics_app_dev
