



default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASS']%>
  host: <%=ENV['DB_HOST']%>
  port: <%=ENV['DB_PORT']%>
  ssl: REQUIRED
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: logistics_app_dev

test:
  <<: *default
  database: logistics_app_test

production:
  <<: *default
  database: logistics_app